namespace Hasm
{
    internal enum Operation
    {
        Nop = 0,
        Move,
        Add,
        Subtract,
        Increment,
        Decrement,
        Multiply,
        Divide,
        Power,
        SquareRoot,
        RandomInteger,
        RandomDouble,
        Sine,
        Cosine,
        Tangent,
        ArcCosine,
        ArcSine,
        ArcTangent,
        Round,
        Push,
        Pop,
        Peek,
        Jump,
        JumpReturnAddress,
        Approx,
        Equal,
        NotEqual,
        GreaterThan,
        GreaterThanOrEqual,
        LesserThan,
        LesserThanOrEqual,
        BranchEqual,
        BranchEqualReturnAddress,
        BranchNotEqual,
        BranchNotEqualReturnAddress,
        BranchGreaterThan,
        BranchGreaterThanReturnAddress,
        BranchGreaterThanOrEqual,
        BranchGreaterThanOrEqualReturnAddress,
        BranchLesserThan,
        BranchLesserThanReturnAddress,
        BranchLesserThanOrEqual,
        BranchLesserThanOrEqualReturnAddress,
        ReadWriteDevice,
        SleepMilliseconds,
        Yield,
#if HASM_FEATURE_MEMORY
        AllocateMemory,
        FreeMemory,
#endif
        
        Assert = 100,
        
        Ret = 1000,
    }
}